### PR TITLE
hidden api key

### PR DESCRIPTION
**Pull request by alejandrods**
- Hidden the api key
- Requirement .env
- Update gitignore

### CODE REVIEW

**Comment by nblackburn** [comment]
There are two problems with this, the code is not built anywhere for those variables to be injected and secondly the key will always be in the commit history.

**Comment by alejandrods** [comment]
> I agree it's not good having keys exposed but considering how this project is constructed there is no other way it could have been done.
> 
> * the code is not built anywhere for those variables to be injected.
> * the key will forever be in the commit history.

Yeah, I agree with you, but there is a way to hide commits with sensitive data:

https://help.github.com/en/articles/removing-sensitive-data-from-a-repository

**Comment by nblackburn** [comment]
@alejandrods Yes, technically it's possible but there is still the problem of their being 55 forks (at the time of writing) with that key in it.

**Comment by nagix** [comment]
Thanks for your suggestion! I have already removed from the API key from this project, generated a new key, and am going to disable the old one soon. Because this application is supposed to run solely on web browsers, it's not possible to completely protect a key. Instead, it should be protected by the Access-Control-Allow-Origin header on the service provider side.

**Pull request closed without merging**
